In [18]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import os 
os.getcwd()

'c:\\Users\\hamoud\\Desktop\\Fraud_detection'

In [19]:
train_data = pd.read_csv("creditcard_train_scaled.csv")
test_data = pd.read_csv("creditcard_test_scaled.csv")
train_data

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V22,V23,V24,V25,V26,V27,V28,scaled_amount,scaled_time,Class
0,-0.917597,1.468375,1.607758,-0.021990,-0.283089,-1.229240,0.753631,-0.146383,-0.231226,0.272734,...,-0.441894,0.050339,0.924543,-0.120948,0.043518,0.484835,0.256764,-0.289650,-0.369625,0
1,-0.699142,0.319290,2.278452,0.736121,-0.684040,0.742862,0.375170,0.367698,-0.234212,-0.523238,...,0.993618,0.085713,0.224880,-0.032720,-0.288623,0.090848,0.074140,1.510490,-0.290133,0
2,-0.571369,1.317794,1.019639,1.021975,-0.042067,-0.127407,0.277220,0.433044,-1.207277,-0.179688,...,0.703393,-0.196171,0.041482,-0.135509,-0.215535,0.043891,0.080868,-0.128951,-0.350920,0
3,1.147507,-1.921087,-0.261885,1.487177,-0.829881,1.908747,-0.955687,0.517632,1.752487,-0.071405,...,0.604139,-0.294560,-0.384808,-0.231287,-0.544888,0.037585,0.036367,5.265734,0.394304,0
4,-0.629345,0.848104,1.146756,0.566688,0.934798,0.073785,0.859693,-0.066140,-0.817268,-0.399711,...,0.023712,-0.422906,-0.992322,0.739840,-0.111136,0.050766,0.068694,0.348951,-0.571407,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227840,0.095639,0.101785,1.261669,-1.375506,-0.519103,-0.233864,-0.100928,-0.147033,-1.281357,0.323678,...,0.105428,-0.029562,-0.351602,-0.957453,1.370403,0.143042,0.177850,-0.096503,0.013436,0
227841,-6.046362,-1.285178,-2.486027,0.271327,-3.502477,0.974063,0.025943,2.182822,0.245799,-1.772681,...,-0.193982,0.159401,-0.541897,-0.645865,0.715113,0.107730,-1.271921,4.024615,-0.047256,0
227842,0.033797,0.882025,0.306073,-0.583187,0.450910,-1.128918,1.033273,-0.231043,-0.107794,-0.422426,...,-0.536077,0.069324,0.050828,-0.475434,0.136317,0.249307,0.098713,-0.257483,0.837261,0
227843,-2.011805,0.510858,0.773423,-1.790730,0.866647,0.349700,0.598281,-0.007178,0.760874,0.809981,...,-0.180485,0.168770,-1.270998,-0.036114,0.810049,0.351317,0.070897,0.111888,-0.347517,0


In [20]:
X_train = train_data.drop(columns="Class")
y_train = train_data["Class"]
print(X_train.shape,y_train.shape)

(227845, 30) (227845,)


In [21]:
X_test = test_data.drop(columns="Class")
y_test = test_data["Class"]
print(X_test.shape,y_test.shape)

(56962, 30) (56962,)


Model training:

Lets create a function that will evaluate and store the models results

In [22]:
import pandas as pd

results_df = pd.DataFrame(columns=[
    "Model",
    "Precision (Non-Fraud)", "Recall (Non-Fraud)", "F1 (Non-Fraud)",
    "Precision (Fraud)", "Recall (Fraud)", "F1 (Fraud)",
    "ROC-AUC"
])

Logistic regression

In [23]:
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression(random_state=42)


In [24]:
from crossval_report import print_crossval_results
lr_model = LogisticRegression(random_state=42)
crossval_result = print_crossval_results(lr_model, X_train, y_train, cv=5)
crossval_result

=== Cross-Validation Classification Report ===
Class 0 (Non-Fraud): Precision=0.999, Recall=1.000, F1=1.000
Class 1 (Fraud)    : Precision=0.871, Recall=0.602, F1=0.712


In [25]:
lr_model.fit(X_train, y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",42
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`multi

In [26]:
y_test_pred = lr_model.predict(X_test)
y_test_proba = lr_model.predict_proba(X_test)[:, 1]
from store_results import store_and_print_results
results_df = store_and_print_results(results_df, "Logistic Rression (Unbalanced)", y_test, y_test_pred, y_test_proba)
results_df

=== Logistic Rression (Unbalanced) Classification Report ===
Class 0 (Non-Fraud): Precision=0.999, Recall=1.000, F1=1.000
Class 1 (Fraud)    : Precision=0.887, Recall=0.643, F1=0.746
ROC-AUC: 0.988



,Model,Precision (Non-Fraud),Recall (Non-Fraud),F1 (Non-Fraud),Precision (Fraud),Recall (Fraud),F1 (Fraud),ROC-AUC
0,Logistic Rression (Unbalanced),0.999385,0.999859,0.999622,0.887324,0.642857,0.745562,0.987716


Logistic Regression Results

1. Cross-Validation (on training set with CV = 5):

    Class 0 (Non-Fraud): Precision = 0.999, Recall = 1.000, F1 = 1.000

    Class 1 (Fraud): Precision = 0.871, Recall = 0.602, F1 = 0.712

    The model detects almost all non-fraud transactions perfectly.

    Fraud detection is weaker (recall 0.602), which is common with highly imbalanced datasets.

2. Test Set Evaluation:

    Class 0 (Non-Fraud): Precision = 0.999, Recall = 1.000, F1 = 1.000

    Class 1 (Fraud): Precision = 0.887, Recall = 0.643, F1 = 0.746

    Performance slightly improves on the test set for fraud detection.


RandomForest


In [27]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight=None  
)
crossval_result= print_crossval_results(rf_model, X_train, y_train, cv=5)
crossval_result

=== Cross-Validation Classification Report ===
Class 0 (Non-Fraud): Precision=1.000, Recall=1.000, F1=1.000
Class 1 (Fraud)    : Precision=0.945, Recall=0.787, F1=0.859


In [28]:
rf_model.fit(X_train, y_train)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",200
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstrap: bool, default=TrueWhether bootstrap samples are used when building trees. If False, thewhole dataset is used to build each tree.",True
,"oob_score oob_score: bool or callable, default=FalseWhether to use out-of-bag samples to estimate the generalization score.By default, :func:`~sklearn.metrics.accuracy_score` is used.Provide a callable with signature `metric

In [29]:
y_test_pred = rf_model.predict(X_test)
y_test_proba = rf_model.predict_proba(X_test)[:, 1]

In [30]:
results_df = store_and_print_results(results_df, "Random Forest (Unbalanced)", y_test, y_test_pred, y_test_proba)
results_df

=== Random Forest (Unbalanced) Classification Report ===
Class 0 (Non-Fraud): Precision=1.000, Recall=1.000, F1=1.000
Class 1 (Fraud)    : Precision=0.950, Recall=0.776, F1=0.854
ROC-AUC: 0.957



,Model,Precision (Non-Fraud),Recall (Non-Fraud),F1 (Non-Fraud),Precision (Fraud),Recall (Fraud),F1 (Fraud),ROC-AUC
0,Logistic Rression (Unbalanced),0.999385,0.999859,0.999622,0.887324,0.642857,0.745562,0.987716
1,Random Forest (Unbalanced),0.999613,0.999930,0.999771,0.950000,0.775510,0.853933,0.956835


1.  Cross-Validation (on training set)

        Class 0 (Non-Fraud): Precision, Recall, F1 = 1.0 → almost perfect at identifying legitimate transactions.

        Class 1 (Fraud):

        Precision = 0.945 → most predicted frauds are truly fraud.

        Recall = 0.787 → ~79% of actual frauds are correctly detected.

        F1 = 0.859 → solid balance between precision and recall for fraud.

2.  Test Set (Unbalanced Random Forest)

        Class 0 (Non-Fraud): Still perfect.

        Class 1 (Fraud):

        Precision = 0.950 → slightly better than CV.

        Recall = 0.776 → slightly lower than CV.

        F1 = 0.854 → very close to CV, showing good generalization.

Non-Fraud Class: Model is enar-perfetct for detecting non-Fraud Class

Fraud Class: Random Forest has higher precision (0.95 vs 0.887) than Logistic Regression, meaning fewer false positives. Recall is also higher (0.776 vs 0.643), meaning more frauds are correctly detected. F1 reflects this improvement.

SGD + Logistic Regression 

In [31]:
from sklearn.linear_model import SGDClassifier
sgd_lr = SGDClassifier(
    loss='log_loss',           
    max_iter=1000,        
    tol=1e-3,             
    class_weight=None,    
    random_state=42
)
crossval_result= print_crossval_results(sgd_lr, X_train, y_train, cv=5)
crossval_result

=== Cross-Validation Classification Report ===
Class 0 (Non-Fraud): Precision=0.999, Recall=1.000, F1=1.000
Class 1 (Fraud)    : Precision=0.842, Recall=0.556, F1=0.670


In [32]:
sgd_lr.fit(X_train,y_train)

,"loss loss: {'hinge', 'log_loss', 'modified_huber', 'squared_hinge', 'perceptron', 'squared_error', 'huber', 'epsilon_insensitive', 'squared_epsilon_insensitive'}, default='hinge'The loss function to be used.- 'hinge' gives a linear SVM.- 'log_loss' gives logistic regression, a probabilistic classifier.- 'modified_huber' is another smooth loss that brings tolerance to outliers as well as probability estimates.- 'squared_hinge' is like hinge but is quadratically penalized.- 'perceptron' is the linear loss used by the perceptron algorithm.- The other losses, 'squared_error', 'huber', 'epsilon_insensitive' and 'squared_epsilon_insensitive' are designed for regression but can be useful in classification as well; see :class:`~sklearn.linear_model.SGDRegressor` for a description.More details about the losses formulas can be found in the :ref:`User Guide` and you can find a visualisation of the lossfunctions in:ref:`sphx_glr_auto_examples_linear_model_plot_sgd_loss_functions.py`.",'log_loss'
,"penalty penalty: {'l2', 'l1', 'elasticnet', None}, default='l2'The penalty (aka regularization term) to be used. Defaults to 'l2'which is the standard regularizer for linear SVM models. 'l1' and'elasticnet' might bring sparsity to the model (feature selection)not achievable with 'l2'. No penalty is added when set to `None`.You can see a visualisation of the penalties in:ref:`sphx_glr_auto_examples_linear_model_plot_sgd_penalties.py`.",'l2'
,"alpha alpha: float, default=0.0001Constant that multiplies the regularization term. The higher thevalue, the stronger the regularization. Also used to compute thelearning rate when `learning_rate` is set to 'optimal'.Values must be in the range `[0.0, inf)`.",0.0001
,"l1_ratio l1_ratio: float, default=0.15The Elastic Net mixing parameter, with 0 <= l1_ratio <= 1.l1_ratio=0 corresponds to L2 penalty, l1_ratio=1 to L1.Only used if `penalty` is 'elasticnet'.Values must be in the range `[0.0, 1.0]` or can be `None` if`penalty` is not `elasticnet`... versionchanged:: 1.7 `l1_ratio` can be `None` when `penalty` is not ""elasticnet"".",0.15
,"fit_intercept fit_intercept: bool, default=TrueWhether the intercept should be estimated or not. If False, thedata is assumed to be already centered.",True
,"max_iter max_iter: int, default=1000The maximum number of passes over the training data (aka epochs).It only impacts the behavior in the ``fit`` method, and not the:meth:`partial_fit` method.Values must be in the range `[1, inf)`... versionadded:: 0.19",1000
,"tol tol: float or None, default=1e-3The stopping criterion. If it is not None, training will stopwhen (loss > best_loss - tol) for ``n_iter_no_change`` consecutiveepochs.Convergence is checked against the training loss or thevalidation loss depending on the `early_stopping` parameter.Values must be in the range `[0.0, inf)`... versionadded:: 0.19",0.001
,"shuffle shuffle: bool, default=TrueWhether or not the training data should be shuffled after each epoch.",True
,"verbose verbose: int, default=0The verbosity level.Values must be in the range `[0, inf)`.",0
,"epsilon epsilon: float, default=0.1Epsilon in the epsilon-insensitive loss functions; only if `loss` is'huber', 'epsilon_insensitive', or 'squared_epsilon_insensitive'.For 'huber', determines the threshold at which it becomes lessimportant to get the prediction exactly right.For epsilon-insensitive, any differences between the current predictionand the correct label are ignored if they are less than this threshold.Values must be in the range `[0.0, inf)`.",0.1
,"n_jobs n_jobs: int, default=NoneThe number of CPUs to use to do the OVA (One Versus All, formulti-class problems) computation.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary `for more details.",None


In [33]:
y_test_pred = sgd_lr.predict(X_test)
y_test_proba = sgd_lr.predict_proba(X_test)[:, 1]

In [34]:
results_df = store_and_print_results(results_df, "SGD_LR (Unbalanced)", y_test, y_test_pred, y_test_proba)
results_df

=== SGD_LR (Unbalanced) Classification Report ===
Class 0 (Non-Fraud): Precision=0.999, Recall=1.000, F1=1.000
Class 1 (Fraud)    : Precision=0.881, Recall=0.602, F1=0.715
ROC-AUC: 0.988



,Model,Precision (Non-Fraud),Recall (Non-Fraud),F1 (Non-Fraud),Precision (Fraud),Recall (Fraud),F1 (Fraud),ROC-AUC
0,Logistic Rression (Unbalanced),0.999385,0.999859,0.999622,0.887324,0.642857,0.745562,0.987716
1,Random Forest (Unbalanced),0.999613,0.999930,0.999771,0.950000,0.775510,0.853933,0.956835
2,SGD_LR (Unbalanced),0.999315,0.999859,0.999587,0.880597,0.602041,0.715152,0.987565


During 5-fold cross-validation on the training set:

        Non-Fraud (Class 0): Precision, Recall, and F1 are essentially perfect (~1.000), meaning the model almost never misclassifies normal transactions.

        Fraud (Class 1): Precision=0.842, Recall=0.556, F1=0.670 — the model identifies many frauds correctly, but still misses a significant portion (recall is moderate).

On the final test set:

        Non-Fraud: Same excellent metrics as CV, showing stable performance.

        Fraud: Precision improved to 0.881, recall to 0.602, F1 to 0.715 — better than CV, likely due to having seen the full training set during final training.

In [35]:
from xgboost import XGBClassifier
xgb_model = XGBClassifier(
    n_estimators=200,
    max_depth=5,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="logloss"
)
crossval_result= print_crossval_results(xgb_model, X_train, y_train, cv=5)
crossval_result

=== Cross-Validation Classification Report ===
Class 0 (Non-Fraud): Precision=1.000, Recall=1.000, F1=1.000
Class 1 (Fraud)    : Precision=0.950, Recall=0.779, F1=0.856


In [36]:
xgb_model.fit(X_train,y_train)

,"objective objective: typing.Union[str, xgboost.sklearn._SklObjWProto, typing.Callable[[typing.Any, typing.Any], typing.Tuple[numpy.ndarray, numpy.ndarray]], NoneType]Specify the learning task and the corresponding learning objective or a customobjective function to be used.For custom objective, see :doc:`/tutorials/custom_metric_obj` and:ref:`custom-obj-metric` for more information, along with the end note forfunction signatures.",'binary:logistic'
,"base_score base_score: typing.Union[float, typing.List[float], NoneType]The initial prediction score of all instances, global bias.",None
,booster,None
,"callbacks callbacks: typing.Optional[typing.List[xgboost.callback.TrainingCallback]]List of callback functions that are applied at end of each iteration.It is possible to use predefined callbacks by using:ref:`Callback API `... note:: States in callback are not preserved during training, which means callback objects can not be reused for multiple training sessions without reinitialization or deepcopy... code-block:: python for params in parameters_grid: # be sure to (re)initialize the callbacks before each run callbacks = [xgb.callback.LearningRateScheduler(custom_rates)] reg = xgboost.XGBRegressor(**params, callbacks=callbacks) reg.fit(X, y)",None
,colsample_bylevel colsample_bylevel: typing.Optional[float]Subsample ratio of columns for each level.,None
,colsample_bynode colsample_bynode: typing.Optional[float]Subsample ratio of columns for each split.,None
,colsample_bytree colsample_bytree: typing.Optional[float]Subsample ratio of columns when constructing each tree.,0.8
,"device device: typing.Optional[str].. versionadded:: 2.0.0Device ordinal, available options are `cpu`, `cuda`, and `gpu`.",None
,"early_stopping_rounds early_stopping_rounds: typing.Optional[int].. versionadded:: 1.6.0- Activates early stopping. Validation metric needs to improve at least once in every **early_stopping_rounds** round(s) to continue training. Requires at least one item in **eval_set** in :py:meth:`fit`.- If early stopping occurs, the model will have two additional attributes: :py:attr:`best_score` and :py:attr:`best_iteration`. These are used by the :py:meth:`predict` and :py:meth:`apply` methods to determine the optimal number of trees during inference. If users want to access the full model (including trees built after early stopping), they can specify the `iteration_range` in these inference methods. In addition, other utilities like model plotting can also use the entire model.- If you prefer to discard the trees after `best_iteration`, consider using the callback function :py:class:`xgboost.callback.EarlyStopping`.- If there's more than one item in **eval_set**, the last entry will be used for early stopping. If there's more than one metric in **eval_metric**, the last metric will be used for early stopping.",None
,enable_categorical enable_categorical: boolSee the same parameter of :py:class:`DMatrix` for details.,False
,"eval_metric eval_metric: typing.Union[str, typing.List[typing.Union[str, typing.Callable]], typing.Callable, NoneType].. versionadded:: 1.6.0Metric used for monitoring the training result and early stopping. It can be astring or list of strings as names of predefined metric in XGBoost (See:doc:`/parameter`), one of the metrics in :py:mod:`sklearn.metrics`, or anyother user defined metric that looks like `sklearn.metrics`.If custom objective is also provided, then custom metric should implement thecorresponding reverse link function.Unlike the `scoring` parameter commonly used in scikit-learn, when a callableobject is provided, it's assumed to be a cost function and by default XGBoostwill minimize the result during early stopping.For advanced usage on Early stopping like directly choosing to maximize insteadof minimize, see :py:obj:`xgboost.callback.EarlyStopping`.See :doc:`/tutorials/custom_metric_obj` and :ref:`custom-obj-metric` for moreinformation... code-block:: python from sklearn.datasets import load_diabetes f

In [37]:
y_test_pred = xgb_model.predict(X_test)
y_test_proba = xgb_model.predict_proba(X_test)[:, 1]
results_df = store_and_print_results(results_df, "XGBoost (Unbalanced)", y_test, y_test_pred, y_test_proba)
results_df

=== XGBoost (Unbalanced) Classification Report ===
Class 0 (Non-Fraud): Precision=1.000, Recall=1.000, F1=1.000
Class 1 (Fraud)    : Precision=0.963, Recall=0.796, F1=0.872
ROC-AUC: 0.986



,Model,Precision (Non-Fraud),Recall (Non-Fraud),F1 (Non-Fraud),Precision (Fraud),Recall (Fraud),F1 (Fraud),ROC-AUC
0,Logistic Rression (Unbalanced),0.999385,0.999859,0.999622,0.887324,0.642857,0.745562,0.987716
1,Random Forest (Unbalanced),0.999613,0.999930,0.999771,0.950000,0.775510,0.853933,0.956835
2,SGD_LR (Unbalanced),0.999315,0.999859,0.999587,0.880597,0.602041,0.715152,0.987565
3,XGBoost (Unbalanced),0.999648,0.999947,0.999798,0.962963,0.795918,0.871508,0.985961


Cross-Validation:

    Non-Fraud: Perfect metrics (precision, recall, F1 ≈ 1.0)

    Fraud: Precision 0.950, Recall 0.779, F1 0.856 → model detects most fraud cases but misses some (recall < 0.8)

Test Set (Unbalanced):

    Non-Fraud remains perfect

    Fraud improves slightly (Precision 0.963, Recall 0.796, F1 0.872)

    ROC-AUC 0.986 → excellent overall discrimination between classes

SVM

In [38]:
from sklearn.svm import SVC

svm_model = SVC(
    kernel='rbf',      
    C=1.0,             
    gamma='scale',
    probability=True,  
    random_state=42
)
from crossval_report import print_crossval_results
crossval_result = print_crossval_results(svm_model, X_train, y_train, cv=3)
crossval_result

=== Cross-Validation Classification Report ===
Class 0 (Non-Fraud): Precision=0.999, Recall=1.000, F1=1.000
Class 1 (Fraud)    : Precision=0.937, Recall=0.645, F1=0.764


In [39]:
svm_model.fit(X_train,y_train)

,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive. The penaltyis a squared l2 penalty. For an intuitive visualization of the effectsof scaling the regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",1.0
,"kernel kernel: {'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'} or callable, default='rbf'Specifies the kernel type to be used in the algorithm. Ifnone is given, 'rbf' will be used. If a callable is given it is used topre-compute the kernel matrix from data matrices; that matrix should bean array of shape ``(n_samples, n_samples)``. For an intuitivevisualization of different kernel types see:ref:`sphx_glr_auto_examples_svm_plot_svm_kernels.py`.",'rbf'
,"degree degree: int, default=3Degree of the polynomial kernel function ('poly').Must be non-negative. Ignored by all other kernels.",3
,"gamma gamma: {'scale', 'auto'} or float, default='scale'Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.- if ``gamma='scale'`` (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma,- if 'auto', uses 1 / n_features- if float, must be non-negative... versionchanged:: 0.22 The default value of ``gamma`` changed from 'auto' to 'scale'.",'scale'
,"coef0 coef0: float, default=0.0Independent term in kernel function.It is only significant in 'poly' and 'sigmoid'.",0.0
,"shrinking shrinking: bool, default=TrueWhether to use the shrinking heuristic.See the :ref:`User Guide `.",True
,"probability probability: bool, default=FalseWhether to enable probability estimates. This must be enabled priorto calling `fit`, will slow down that method as it internally uses5-fold cross-validation, and `predict_proba` may be inconsistent with`predict`. Read more in the :ref:`User Guide `.",True
,"tol tol: float, default=1e-3Tolerance for stopping criterion.",0.001
,"cache_size cache_size: float, default=200Specify the size of the kernel cache (in MB).",200
,"class_weight class_weight: dict or 'balanced', default=NoneSet the parameter C of class i to class_weight[i]*C forSVC. If not given, all classes are supposed to haveweight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.",None
,"verbose verbose: bool, default=FalseEnable verbose output. Note that this setting takes advantage of aper-process runtime setting in libsvm that, if enabled, may not workproperly in a multithreaded context.",False


In [40]:
y_test_pred = svm_model.predict(X_test)
y_test_proba = svm_model.predict_proba(X_test)[:, 1]
from store_results import store_and_print_results
results_df = store_and_print_results(results_df, "SVM (Unbalanced)", y_test, y_test_pred, y_test_proba)
results_df

=== SVM (Unbalanced) Classification Report ===
Class 0 (Non-Fraud): Precision=0.999, Recall=1.000, F1=1.000
Class 1 (Fraud)    : Precision=0.971, Recall=0.684, F1=0.802
ROC-AUC: 0.940



,Model,Precision (Non-Fraud),Recall (Non-Fraud),F1 (Non-Fraud),Precision (Fraud),Recall (Fraud),F1 (Fraud),ROC-AUC
0,Logistic Rression (Unbalanced),0.999385,0.999859,0.999622,0.887324,0.642857,0.745562,0.987716
1,Random Forest (Unbalanced),0.999613,0.999930,0.999771,0.950000,0.775510,0.853933,0.956835
2,SGD_LR (Unbalanced),0.999315,0.999859,0.999587,0.880597,0.602041,0.715152,0.987565
3,XGBoost (Unbalanced),0.999648,0.999947,0.999798,0.962963,0.795918,0.871508,0.985961
4,SVM (Unbalanced),0.999455,0.999965,0.999710,0.971014,0.683673,0.802395,0.939697


During 5-fold cross-validation, the SVM model achieved almost perfect performance for the non-fraud class, with precision, recall, and F1-score all close to 1.000. For the fraud class, the model obtained a precision of 0.937, recall of 0.645, and F1-score of 0.764. This indicates that when the model predicts fraud it is usually correct, but it still misses a noticeable number of fraudulent transactions.

When evaluated on the test set, the performance improved slightly. The fraud class achieved a precision of 0.971, recall of 0.684, and F1-score of 0.802. The ROC-AUC score of 0.940 indicates that the model has a strong ability to distinguish between fraudulent and legitimate transactions overall.

LIGHTGBM


In [41]:
from lightgbm import LGBMClassifier
lgbm_model = LGBMClassifier(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=-1,
    num_leaves=31,
    random_state=42
)
crossval_result = print_crossval_results(lgbm_model, X_train, y_train, cv=5)
crossval_result

[LightGBM] [Info] Number of positive: 316, number of negative: 181960
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0,006513 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7650
[LightGBM] [Info] Number of data points in the train set: 182276, number of used features: 30
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0,001734 -> initscore=-6,355800
[LightGBM] [Info] Start training from score -6,355800
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gai

In [42]:
lgbm_model.fit(X_train, y_train)

[LightGBM] [Info] Number of positive: 394, number of negative: 227451
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0,007587 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7650
[LightGBM] [Info] Number of data points in the train set: 227845, number of used features: 30
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0,001729 -> initscore=-6,358339
[LightGBM] [Info] Start training from score -6,358339


,boosting_type,'gbdt'
,num_leaves,31
,max_depth,-1
,learning_rate,0.1
,n_estimators,200
,subsample_for_bin,200000
,objective,None
,class_weight,None
,min_split_gain,0.0
,min_child_weight,0.001
,min_child_samples,20


In [43]:
y_test_pred = lgbm_model.predict(X_test)
y_test_proba = lgbm_model.predict_proba(X_test)[:, 1]

results_df = store_and_print_results(
    results_df,
    "LightGBM (Unbalanced)",
    y_test,
    y_test_pred,
    y_test_proba
)

results_df

=== LightGBM (Unbalanced) Classification Report ===
Class 0 (Non-Fraud): Precision=0.998, Recall=0.991, F1=0.995
Class 1 (Fraud)    : Precision=0.022, Recall=0.122, F1=0.038
ROC-AUC: 0.575



,Model,Precision (Non-Fraud),Recall (Non-Fraud),F1 (Non-Fraud),Precision (Fraud),Recall (Fraud),F1 (Fraud),ROC-AUC
0,Logistic Rression (Unbalanced),0.999385,0.999859,0.999622,0.887324,0.642857,0.745562,0.987716
1,Random Forest (Unbalanced),0.999613,0.999930,0.999771,0.950000,0.775510,0.853933,0.956835
2,SGD_LR (Unbalanced),0.999315,0.999859,0.999587,0.880597,0.602041,0.715152,0.987565
3,XGBoost (Unbalanced),0.999648,0.999947,0.999798,0.962963,0.795918,0.871508,0.985961
4,SVM (Unbalanced),0.999455,0.999965,0.999710,0.971014,0.683673,0.802395,0.939697
5,LightGBM (Unbalanced),0.998476,0.990732,0.994589,0.022263,0.122449,0.037677,0.575404
